### ISSUE TITLE
how to migrate django for existing postgres-xl?

### ISSUE THREAD

**Issue by m-karbasi** [JBKahn/django-sharding#83]
hello dear,
i have an application by postgres-xl database, i am going to create admin panel in django admin, but when migrating i get this error : 
```python
with_wrappers
    return executor(sql, params, many, context)
  File "/home/mk/.local/share/virtualenvs/admin_panel/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mk/.local/share/virtualenvs/admin_panel/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mk/.local/share/virtualenvs/admin_panel/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: Unique index of partitioned table must contain the hash distribution column.
```
does django sharding solve my problem?

thanks in advance

**Comment by JBKahn** [comment]
Is this a model you've defined? A built in one?

**Comment by omidraha** [comment]
Hi, I have the same issue on sample django app for `contenttypes` model of django on the first django built-in migration file:
```
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, ads, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):

django.db.utils.ProgrammingError: Unique index of partitioned table must contain the hash distribution column.
```
I just use `Postgres-XL`n and wihtout  using`django-sharding` module.

Do you have any idea about this error?
